# Page settings

baseURL = "https://burlesco70.github.io/"
languageCode = "en"
title = "CV Mario Nardi"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Mario Nardi"
    description = "CV using Hugo and DevResume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Mario Nardi"
        tagline = "Senior IT Specialist"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Biella, Piedmont, Italy"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:mario.nardi.70@gmail.com"
        text = "mario.nardi.70"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://linkedin.com/in/mario-nardi-017705100/"
        text = "Linkedin"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"
        [[params.skills.list.items]]
        details = "Manage remote teams"
        [[params.skills.list.items]]
        details = "Design and implement services"
        [[params.skills.list.items]]
        details = "Python/SQL"
        [[params.skills.list.items]]
        details = "Confluence/Jira"


        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Good time management"
        [[params.skills.list.items]]
        details = "Effective communication"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Computer Science"
        university = "University of Turin"
        dates = "1989 – 1994"
        [[params.education.list]]
        degree = "Certified ScrumMaster ®"
        university = "Scrum Alliance"
        dates = "2015"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Italian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Spanish"
        level = "Amateur"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Trekking"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "I am a self-motivated professional, with almost 25 years of experience as Software Engineer: business analysis, design, development, testing and release process. Making banking business real."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Centrico"
        details = "Focused on agile planning, business process management and analysis, project management and problem solving in the Banking Payment Systems area."
        [[params.experience.list.items]]
        details = "Smart Business Sella platform: providing services for onboarding and payments"
        [[params.experience.list.items]]
        details = "Trade Finance: re-engineering legacy environment links"
        [[params.experience.list.items]]
        details = "Illimity Bank and Hype: follow up and gaps management"
        [[params.experience.list.items]]
        details = "Bill Payments, Remote Banking, Tax payment application:business and technical evolution management"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "1996 - 2019"
        company = "Banca Sella"
        details = "I've played most of IT roles, from Cobol and Java programmer to technical and business analyst on projects of Payments area"
        [[params.experience.list.items]]
        details = "CBILL payments as a service"
        [[params.experience.list.items]]
        details = "PagoPA payments as a service"
        [[params.experience.list.items]]
        details = "New Bank For Business Remote Banking platform"
        [[params.experience.list.items]]
        details = "Postal Bills payments as a service"
        [[params.experience.list.items]]
        details = "Credit transfers: migration to SEPA SCT"
        [[params.experience.list.items]]
        details = "Credit transfers: managing batch payments from CBI"
        [[params.experience.list.items]]
        details = "... and many others"












    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Biella Python Group"
        meta = "Programming Python"
        tagline = "In the board of local Python user group"

        [[params.projects.list]]
        title = "B4FUN"
        meta = "Programming Godot"
        tagline = "Small projects on gaming"

        [[params.projects.list]]
        title = "Prima di Mezzanotte"
        meta = "Writing"
        tagline = "Founder member"

        [[params.projects.list]]
        title = "Fotoclub Biella"
        meta = "Photography"
        tagline = "Group member"










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Trekking, Photography, Writing , Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/Burlesco70"
        title = "Burlesco70"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/mario-nardi-017705100/"
        title = "Mario Nardi"





